version: '3.2'
services:
  app:
    image: ssnukala/uf4xphp:4.5.0.01
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: docker-app/Dockerfile
    volumes:
      - ./docker-app/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/.composer/docker-cache/:/root/.composer:cached
